export const data = [
  {
    id: 1,
    // avatar: "./iceland/iceland-thumb-1.jpg",
    text: "Talk is cheap. Show me the code.",
    metadata: "Author: Linus Torvalds",
  },
  {
    id: 2,
    // avatar: "./iceland/iceland-thumb-2.jpg",
    text: "Programs must be written for people to read, and only incidentally for machines to execute.",
    metadata: "Author: Harold Abelson",
  },
  {
    id: 3,
    // avatar: "./iceland/iceland-thumb-3.jpg",
    text: "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live",
    metadata: "Author: John Woods",
  },
  {
    id: 4,
    // avatar: "./iceland/iceland-thumb-4.jpg",
    text: "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.",
    metadata: "Author: Rick Cook",
  },
  {
    id: 5,
    // avatar: "./iceland/iceland-thumb-5.jpg",
    text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    metadata: "Author: Martin Fowler",
  },
  {
    id: 6,
    // avatar: "./iceland/iceland-thumb-6.jpg",
    text: "Well, Mr. Frankel, who started this program, began to suffer from the computer disease that anybody who works with computers now knows about. It's a very serious disease and it interferes completely with the work. The trouble with computers is you *play* with them. They are so wonderful. You have these switches - if it's an even number you do this, if it's an odd number you do that - and pretty soon you can do more and more elaborate things if you are clever enough, on one machine.",
    metadata: "Author: Richard P. Feynman",
  },
  {
    id: 7,
    // avatar: "./iceland/iceland-thumb-7.jpg",
    text: "The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly. A programmer is ideally an essayist who works with traditional aesthetic and literary forms as well as mathematical concepts, to communicate the way that an algorithm works and to convince a reader that the results will be correct.",
    metadata: "Author: Donald E. Knuth",
  },
  {
    id: 8,
    // avatar: "./iceland/iceland-thumb-8.jpg",
    text: "Punishments include such things as flashbacks, flooding of unbearable emotions, painful body memories, flooding of memories in which the survivor perpetrated against others, self-harm, and suicide attempts.",
    metadata: "Author: Alison Miller",
  },
  {
    id: 9,
    // avatar: "./iceland/iceland-thumb-9.jpg",
    text: "I'm not a great programmer; I'm just a good programmer with great habits.",
    metadata: "Author: Kent Beck",
  },
  {
    id: 10,
    // avatar: "./iceland/iceland-thumb-10.jpg",
    text: "Truth can only be found in one place: the code.",
    metadata: "Author: Robert C. Martin",
  },
  {
    id: 11,
    // avatar: "./iceland/iceland-thumb-11.jpg",
    text: "Give a man a program, frustrate him for a day.",
    metadata: "Author: Muhammad Waseem",
  },
  {
    id: 12,
    // avatar: "./iceland/iceland-thumb-12.jpg",
    text: "That's the thing about people who think they hate computers. What they really hate is lousy programmers.",
    metadata: "Author: Larry Niven",
  },
  {
    id: 13,
    // avatar: "./iceland/iceland-thumb-13.jpg",
    text: "How you look at it is pretty much how you'll see it",
    metadata: "Author: Rasheed Ogunlaru",
  },
  {
    id: 14,
    // avatar: "./iceland/iceland-thumb-14.jpg",
    text: "You've baked a really lovely cake, but then you've used dog shit for frosting.",
    metadata: "Author: Steve Jobs",
  },
  {
    id: 15,
    // avatar: "./iceland/iceland-thumb-15.jpg",
    text: "A language that doesn't affect the way you think about programming is not worth knowing.",
    metadata: "Author: Alan J. Perlis",
  },
  {
    id: 16,
    // avatar: "./iceland/iceland-thumb-16.jpg",
    text: "Walking on water and developing software from a specification are easy if both are frozen.",
    metadata: "Author: Edward V. Berard",
  },
  {
    id: 17,
    // avatar: "./iceland/iceland-thumb-17.jpg",
    text: "On two occasions, I have been asked [by members of Parliament], 'Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?' I am not able to rightly apprehend the kind of confusion of ideas that could provoke such a question.",
    metadata: "Author: Charles Babbage",
  },
  {
    id: 18,
    // avatar: "./iceland/iceland-thumb-18.jpg",
    text: "The most disastrous thing that you can ever learn is your first programming language.",
    metadata: "Author: Alan Kay",
  },
  {
    id: 19,
    // avatar: "./iceland/iceland-thumb-19.jpg",
    text: "The computer programmer is a creator of universes for which he alone is the lawgiver. No playwright, no stage director, no emperor, however powerful, has ever exercised such absolute authority to arrange a stage or field of battle and to command such unswervingly dutiful actors or troops.",
    metadata: "Author: Joseph Weizenbaum",
  },
  {
    id: 20,
    // avatar: "./iceland/iceland-thumb-20.jpg",
    text: "Perl – The only language that looks the same before and after RSA encryption.",
    metadata: "Author: Keith Bostic",
  },
];
